langugage: php

php:
  - 7.2

env:
  global:
    - SIMPLETEST_DB=sqlite://tmp/site.sqlite
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
    - COMPOSER_MEMORY_LIMIT=-1
  matrix:
    - RELEASE=stable COMPOSER_CHANNEL=stable
    - RELEASE=stable COMPOSER_CHANNEL=snapshot

services:
  - memcached

before_install:
  # add extension for memcache
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # increase memorry limit
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # setup sendmail path
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # disable xdebug
  - phpenv config-rm xdebug.ini
  # update composer
  - composer clear-cache
  - composer --verbose self-update --$COMPOSER_CHANNEL
  - composer --version

install:
  - composer --verbose validate
  - composer --verbose create-project opengov/opengov-project:dev-master opengov-project --prefer-dist --no-interaction
  - cd $TRAVIS_BUILD_DIR/opengov-project/html
  - ./../vendor/bin/drush site-install og --verbose --yes --db-url=sqlite://tmp/site.sqlite --account-name test --account-pass test

script:
  # clear cache
  - ./../vendor/bin/drush cr
  
  # check response
  - ./../vendor/bin/drush runserver $SIMPLETEST_BASE_URL &
  - until curl -s $SIMPLETEST_BASE_URL; do true; done > /dev/null
